package com.example.lit_fits_application.entities;

import java.io.File;
import java.io.Serializable;
import java.util.Objects;
import java.util.Set;

/**
 * Garment entity
 *
 * @author Charlie
 */
public class Garment implements Serializable {
    private static final long serialVersionUID = 1L;
    /**
     * Unique id of the Garment
     */
    private long id;
    /**
     * Unique barcode identifier of the garment
     */
    private String barcode;
    /**
     * The person that designed the garment
     */
    private String designer;
    /**
     * How much is worth
     */
    private Double price;
    /**
     * The kind of situation is suited for
     */
    private Mood mood;
    /**
     * Where it is worn
     */
    private BodyPart bodyPart;
    /**
     * What kind of garment it is
     */
    private GarmentType garmentType;
    /**
     * Indicates if it can be bought
     */
    private Boolean available;
    /**
     * Indicates if the company requested a promotion for this garment
     */
    private Boolean promotionRequest;
    /**
     * Indicates if the promotion request is accepted
     */
    private Boolean promoted;
    /**
     * Path in the database to the picture of the garment
     */
    private String imagePath; // Do i even need this in the client?
    /**
     * Company that sells the garment
     */
    private Company company;
    /**
     * What colors are in the garment
     */
    private Set<Color> colors;
    /**
     * What materials is the garment made out of
     */
    private Set<Material> materials;
    /**
     * The picture of the garment
     */
    private File picture;

    /**
     * Empty constructor
     */
    public Garment() {
    }

    /**
     * Full constructor, except for the id as it is auto-generated by the server
     *
     * @param barcode
     * @param designer
     * @param price
     * @param mood
     * @param bodyPart
     * @param garmentType
     * @param available
     * @param promotionRequest
     * @param promoted
     * @param imagePath
     * @param company
     * @param colors
     * @param materials
     * @param picture
     */
    public Garment(String barcode, String designer, Double price, Mood mood, BodyPart bodyPart, GarmentType garmentType, boolean available, boolean promotionRequest, boolean promoted, String imagePath, Company company, Set<Color> colors, Set<Material> materials, File picture) {
        this.barcode = barcode;
        this.designer = designer;
        this.price = price;
        this.mood = mood;
        this.bodyPart = bodyPart;
        this.garmentType = garmentType;
        this.available = available;
        this.promotionRequest = promotionRequest;
        this.promoted = promoted;
        this.imagePath = imagePath;
        this.company = company;
        this.colors = colors;
        this.materials = materials;
        this.picture = picture;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getBarcode() {
        return this.barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode=barcode;
    }

    public String getDesigner() {
        return this.designer;
    }

    public void setDesigner(String designer) {
        this.designer=designer;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Mood getMood() {
        return this.mood;
    }

    public void setMood(Mood mood) {
        this.mood = mood;
    }

    public BodyPart getBodyPart() {
        return this.bodyPart;
    }

    public void setBodyPart(BodyPart bodyPart) {
        this.bodyPart = bodyPart;
    }

    public GarmentType getGarmentType() {
        return this.garmentType;
    }

    public void setGarmentType(GarmentType garmentType) {
        this.garmentType = garmentType;
    }

    public boolean isAvailable() {
        return this.available;
    }

    public void setAvailable(boolean available) {
        this.available = available;
    }

    public boolean isPromotionRequest() {
        return this.promotionRequest;
    }

    public void setPromotionRequest(boolean promotionRequest) {
        this.promotionRequest = promotionRequest;
    }

    public boolean isPromoted() {
        return this.promoted;
    }

    public void setPromoted(boolean promoted) {
        this.promoted = promoted;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    public Set<Color> getColors() {
        return this.colors;
    }

    public void setColors(Set<Color> colors) {
        this.colors = colors;
    }

    public Set<Material> getMaterials() {
        return this.materials;
    }

    public void setMaterials(Set<Material> materials) {
        this.materials = materials;
    }

    public File getPicture() {
        return this.picture;
    }

    public void setPicture(File picture) {
        this.picture = picture;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + (int) (this.id ^ (this.id >>> 32));
        hash = 59 * hash + Objects.hashCode(this.barcode);
        hash = 59 * hash + Objects.hashCode(this.designer);
        hash = 59 * hash + Objects.hashCode(this.price);
        hash = 59 * hash + Objects.hashCode(this.mood);
        hash = 59 * hash + Objects.hashCode(this.bodyPart);
        hash = 59 * hash + Objects.hashCode(this.garmentType);
        hash = 59 * hash + Objects.hashCode(this.available);
        hash = 59 * hash + Objects.hashCode(this.promotionRequest);
        hash = 59 * hash + Objects.hashCode(this.promoted);
        hash = 59 * hash + Objects.hashCode(this.imagePath);
        hash = 59 * hash + Objects.hashCode(this.company);
        hash = 59 * hash + Objects.hashCode(this.colors);
        hash = 59 * hash + Objects.hashCode(this.materials);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Garment other = (Garment) obj;
        if (this.id != other.id) {
            return false;
        }
        if (this.available != other.available) {
            return false;
        }
        if (this.promotionRequest != other.promotionRequest) {
            return false;
        }
        if (this.promoted != other.promoted) {
            return false;
        }
        if (!Objects.equals(this.barcode, other.barcode)) {
            return false;
        }
        if (!Objects.equals(this.designer, other.designer)) {
            return false;
        }
        if (!Objects.equals(this.imagePath, other.imagePath)) {
            return false;
        }
        if (!Objects.equals(this.price, other.price)) {
            return false;
        }
        if (this.mood != other.mood) {
            return false;
        }
        if (this.bodyPart != other.bodyPart) {
            return false;
        }
        if (this.garmentType != other.garmentType) {
            return false;
        }
        if (!Objects.equals(this.company, other.company)) {
            return false;
        }
        if (!Objects.equals(this.colors, other.colors)) {
            return false;
        }
        return Objects.equals(this.materials, other.materials);
    }

    @Override
    public String toString() {
        return "Garment{" + "id=" + id + ", barcode=" + barcode + ", designer=" + designer + ", price=" + price + ", mood=" + mood + ", bodyPart=" + bodyPart + ", garmentType=" + garmentType + ", available=" + available + ", promotionRequest=" + promotionRequest + ", promoted=" + promoted + ", imagePath=" + imagePath + ", company=" + company + ", colors=" + colors + ", materials=" + materials + '}';
    }
}
